package main

import (
	"fmt"
	"math/rand"
	"time"

	"stash.skybet.net/~sorsbyl/conways/utils"
)

func generateInitialGrid() [][]bool {
	return [][]bool{
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
		{false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false},
	}
}

func randomiseGrid() [][]bool {
	grid := generateInitialGrid()

	rand.Seed(time.Now().UnixNano())
	rand.Shuffle(len(grid), func(i, j int) {
		grid[i][j] = grid[j][i]
	})
	return grid
}

func printGrid(grid [][]bool) {
	for {
		for _, row := range grid {
			for _, item := range row {
				if item {
					fmt.Print(" ⬛ ")
				} else {
					fmt.Print(" ⬜ ")
				}
			}
			fmt.Println()
		}

		time.Sleep(700 * time.Millisecond)
		clearScreen()
		grid = utils.Evaluate(grid)
	}
}

func clearScreen() {
	print("\033[H\033[2J")
}

func main() {
	clearScreen()
	grid := randomiseGrid()
	printGrid(grid)
}
